// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (non-pooled) connection — used by Prisma CLI for migrations.
    // The app's PrismaClient uses the pooled DATABASE_URL at runtime instead (see src/lib/prisma.ts).
    url: process.env["DIRECT_URL"],
  },
});
